### ISSUE TITLE
SDK Can't be Used to Download Attachment Data

### ISSUE THREAD

**Issue by provoaggie** [ringcentral/php-sdk#1]
I am using:

$attachment = "https://platform.devtest.ringcentral.com/restapi/v1.0/account/130980004/extension/130980004/message-store/1146871004/content/1146871004";
$res2 = $rcsdk->getPlatform()->get($attachment);
file_put_contents("file.pdf",$res2->getBody());

This grabs the content and creates a file that is 189KB (It's a few bytes off the size of the PDF I get from logging into my account). The file that it creates though is corrupt thought. It appears that the data returned by getBody() isn't usable for creating a valid file. Either that method should be updated to retrieve proper data or a new method should be created.

**Comment by kirill-konshin** [comment]
Use the following method to retrieve attachment URL with credentials:

```php
$urlWithCredentials = $platform->apiUrl($attachment, array('addToken' => true));
```
