### ISSUE TITLE
Subscription class not in autoloader

### ISSUE THREAD

**Issue by ralph3991** [ringcentral/php-sdk#2]
<?php

require_once('vendor/autoload.php');

// Configuration
define('SANDBOX', 1);
define('BASE_URL', SANDBOX ? 'https://platform.devtest.ringcentral.com' : 'https://platform.ringcentral.com');
define('KEY', 'C3Kovxb2T9a7MYMmyhnv3A');
define('SECRET', 'JJ-NjL0MSHyjdywa5t4B4QHE-AF_NRRcq-ePM-o6Chbg');
define('USERNAME', '15856234168'); // Main Phone Number
define('PASSWORD', 'HKWXMX75934&H');

$rcsdk = new RC\SDK(KEY, SECRET, BASE_URL);
$rcsdk->getPlatform()->authorize(USERNAME, '', PASSWORD, true);
$rcsdk->getPlatform()->isAuthorized();

function getVoiceMails() {
    if ($rcsdk->getPlatform()->isAuthorized()) {
        try {
            $response = $rcsdk->getPlatform()->get('/account/~/extension/~/message-store?messageType=VoiceMail');
        } catch (RC\http\HttpException $e) {
            print 'Expected HTTP Error: ' . $e->getResponse()->getError() . PHP_EOL;
        }

        return $response->getJson();
    }
}

$rcsdk->getSubscription()
    ->addEvents(array('/restapi/v1.0/account/~/extension/~/presence'))
    ->on(Subscription::EVENT_NOTIFICATION, function (NotificationEvent $e) {

        print_r($e->getPayload());

    })
    ->register();

PHP Fatal error:  Class 'Subscription' not found in /home/rafael/PhpstormProjects/ringcentral-vm/program.php on line 37

Was this done intentionally?

**Comment by kirill-konshin** [comment]
You have to add

'''php
use RC\subscription\Subscription;
'''

statement or refer to the full name of class: 'RC\subscription\Subscription'.

**Comment by ralph3991** [comment]
Should it not be included in the autoloader?

**Comment by kirill-konshin** [comment]
Autoloader only tells php where to locate files, so it's already covered by Autoloader.

In the rest of your code you use full class names and it works, so do the same for subscription. Or have one use statement at the top of your file.

**Comment by ralph3991** [comment]
Okay thank you very much. I was confused about autoloading but you cleared it up.

**Comment by kirill-konshin** [comment]
No problem :)

**Comment by ralph3991** [comment]
Receiving this error. I don't want to change protected to public without your advice.

### Stack Trace
````php
PHP Fatal error:  Call to protected method RC\subscription\Subscription::notify() from context 'Pubnub\Pubnub' in /home/rafael/PhpstormProjects/ringcentral-vm/vendor/pubnub/pubnub/composer/lib/Pubnub/Pubnub.php on line 468
PHP Stack trace:
PHP   1. {main}() /home/rafael/PhpstormProjects/ringcentral-vm/program.php:0
PHP   2. VMDownloader->startListener() /home/rafael/PhpstormProjects/ringcentral-vm/program.php:62
PHP   3. RC\subscription\Subscription->register($options = *uninitialized*) /home/rafael/PhpstormProjects/ringcentral-vm/program.php:44
PHP   4. RC\subscription\Subscription->subscribe($options = *uninitialized*) /home/rafael/PhpstormProjects/ringcentral-vm/vendor/ringcentral/php-sdk/lib/RC/subscription/Subscription.php:76
PHP   5. RC\subscription\Subscription->subscribeAtPubnub() /home/rafael/PhpstormProjects/ringcentral-vm/vendor/ringcentral/php-sdk/lib/RC/subscription/Subscription.php:119
PHP   6. Pubnub\Pubnub->subscribe($channel = *uninitialized*, $callback = *uninitialized*, $timeToken = *uninitialized*, $presence = *uninitialized*) /home/rafael/PhpstormProjects/ringcentral-vm/vendor/ringcentral/php-sdk/lib/RC/subscription/Subscription.php:241
PHP   7. Pubnub\Pubnub->_subscribe($channel = *uninitialized*, $channelGroup = *uninitialized*, $callback = *uninitialized*, $timeToken = *uninitialized*, $presence = *uninitialized*) /home/rafael/PhpstormProjects/ringcentral-vm/vendor/pubnub/pubnub/composer/lib/Pubnub/Pubnub.php:365
````

### Program.php
````php
<?php

require_once('vendor/autoload.php');

use \RC\SDK;
use \RC\subscription\events\NotificationEvent;
use \RC\subscription\Subscription;

class VMDownloader
{
    // Configuration
    const KEY         = 'C3Kovxb2T9a7MYMmyhnv3A';
    const SECRET      = 'JJ-NjL0MSHyjdywa5t4B4QHE-AF_NRRcq-ePM-o6Chbg';
    const SERVER      = 'https://platform.devtest.ringcentral.com';
    const MAIN_NUMBER = '15856234168';
    const PASSWORD    = 'HKWXMX75934&H';

    private $sdk;

    function __construct()
    {
        $this->sdk = new SDK(self::KEY, self::SECRET, self::SERVER);
        $this->sdk->getPlatform()->authorize(self::MAIN_NUMBER, '', self::PASSWORD, true);
    }

    public function getVoicemails()
    {
        return $this->sdk->getPlatform()
            ->get('/account/~/extension/~/message-store', ['messageType' => 'VoiceMail'])
            ->getJson();
    }

    /**
     * Listens for new messages
     */
    public function startListener()
    {
        $this->sdk->getSubscription()
            ->addEvents(['/restapi/v1.0/account/~/extension/~/message-store'])
            ->on(Subscription::EVENT_NOTIFICATION, function (NotificationEvent $e) {

                print_r($e->getPayload());

                // TODO: Add curl downloader

            })
            ->register();
    }

    /**
     * @todo finish function definition
     */
    private function download()
    {
    }

    function __destructor()
    {
        print 'Destroyed';
    }
}

$t = new VMDownloader();

$t->startListener();
````

**Comment by kirill-konshin** [comment]
What version of PHP do you have?

**Comment by ralph3991** [comment]
```
rafael@rcepeda:~/Downloads/PhpStorm-141.1912/bin$ php -v
PHP 5.6.4-4ubuntu6.2 (cli) (built: Jul  2 2015 15:29:28) 
```

**Comment by kirill-konshin** [comment]
I've pushed a small fix for your case, go ahead and try. The fix is in DEVELOP branch.

**Comment by ralph3991** [comment]
Thank you sir.

**Comment by grokify** [comment]
@ralph3991: I replaced the app and user credentials with placeholders in your posts. For security purposes, please don't post your app and user credentials online.

**Comment by ralph3991** [comment]
okay, since it was a sandbox, I did not mind it. But I gotcha
